### ISSUE TITLE
GET_KEY.md requires light updating

### ISSUE THREAD

**Issue by jungbluth** [kiblee/tod0#36]
Microsoft Azure expectedly continues development. With this in mind, at least one of the steps in the GET_KEY.md file seems outdated. In step three it's no longer clear how one selects "Platform configuration: Client Application" - this selection seems missing on the "Register an application" page. I've not have tod0 working in recent history, so that's all I can say for now. Thanks!

**Comment by kiblee** [comment]
Fixed! Thanks for opening this!
