### ISSUE TITLE
can not connect to localhost

### ISSUE THREAD

**Issue by domingoUnican** [kiblee/tod0#42]
Dear community, 
I am trying to use Tod0 but after registering the app in azure, write the command `todocli ls` in the terminal, it gives me an url to authorize which does not work. Is there any other step that I am missing?

**Comment by kiblee** [comment]
Hi. Could you explain how the url doesn't work? Once you are authenticated in the browser you will see some kind of an error, which is normal. You just need to copy the entire url from the browser to the terminal. Hope that makes sense.
