### ISSUE TITLE
Input redirect url error

### ISSUE THREAD

**Issue by shejialuo** [kiblee/tod0#48]
**Describe the bug**

Now, the text interface for inputing redirect url is  messy.

![image](https://user-images.githubusercontent.com/56911263/195593532-d9bbecd3-f24f-4ddd-b298-0a1f281563b3.png)

I think the reason is here.

https://github.com/kiblee/tod0/blob/a869c8ef313ea5a50e757b44b66a5ca8a1ad17b0/todocli/interface.py#L118-L119

**Comment by kiblee** [comment]
Thanks. Fixed!
