### ISSUE TITLE
Works great but -i for interactive mode is always on

### ISSUE THREAD

**Issue by rjoungatelite** [kiblee/tod0#60]
Excellent CLI utility, want to invoke in Windows 11 batch file, but it prompts for additional action after entering task correctly into the default list.  The -i option in the readme returns 'todocli: error: unrecognized arguments: -i', as far as I can tell it's invoked in interactive mode to begin with and I can't switch that off.

**Comment by kiblee** [comment]
@rjoungatelite I've created a new release with all recent changes. Hope that helps.
